"""Briefing document generation for stakeholder presentations."""

import logging
import os

from config.project_config import ANALYSIS_DIR, OUTPUT_DIR
from utils.db_utils import format_dollars

logger = logging.getLogger('medicaid_fwa.export')


def generate_briefing_document(summary_stats, top_findings, output_dir=None):
    """Generate a structured briefing document in markdown.

    Args:
        summary_stats: dict with pipeline-level statistics.
        top_findings: List of top finding dicts for the briefing.
        output_dir: Output directory.

    Returns:
        Path to generated briefing document.
    """
    output_dir = output_dir or os.path.join(OUTPUT_DIR, 'packages', 'briefing')
    os.makedirs(output_dir, exist_ok=True)

    total_paid = summary_stats.get('total_paid_analyzed', 0)
    total_providers = summary_stats.get('total_providers', 0)
    total_findings = summary_stats.get('total_findings', 0)
    estimated_recoverable = summary_stats.get('estimated_recoverable', 0)

    lines = [
        '# Medicaid FWA Analytics Briefing',
        '',
        '## Key Metrics',
        '',
        f'- **Total Payments Analyzed:** {format_dollars(total_paid)}',
        f'- **Providers Evaluated:** {total_providers:,}',
        f'- **Total Findings:** {total_findings:,}',
        f'- **Estimated Recoverable:** {format_dollars(estimated_recoverable)}',
        '',
        '## Top Priority Findings',
        '',
    ]

    for i, f in enumerate(top_findings[:10], 1):
        npi = f.get('npi', f.get('flagged_providers', ['Unknown'])[0])
        impact = f.get('total_impact', 0)
        method = f.get('method_name', 'Unknown')
        confidence = f.get('confidence', 0)
        lines.append(f'{i}. **NPI {npi}** — {format_dollars(impact)} '
                      f'({method}, confidence {confidence:.0%})')

    lines.extend([
        '',
        '## Recommended Actions',
        '',
        '1. Prioritize review of high-confidence, high-impact providers',
        '2. Refer LEIE-matched providers for immediate investigation',
        '3. Initiate peer comparison audits for statistical outliers',
        '4. Review network analysis findings for organized fraud indicators',
        '',
        '---',
        '',
        '*Generated by Medicaid FWA Analytics Pipeline*',
    ])

    path = os.path.join(output_dir, 'fwa_briefing.md')
    with open(path, 'w') as f:
        f.write('\n'.join(lines))

    logger.info(f'Generated briefing document: {path}')
    return path
