"""Plain-language narrative generation for non-technical stakeholders."""

import logging
import os

from config.project_config import OUTPUT_DIR
from utils.db_utils import format_dollars

logger = logging.getLogger('medicaid_fwa.export')


def generate_narrative_summary(summary_stats, top_findings, output_dir=None):
    """Generate a plain-language narrative summary of pipeline results.

    Args:
        summary_stats: dict with pipeline-level statistics.
        top_findings: List of top finding dicts.
        output_dir: Output directory.

    Returns:
        Path to generated narrative document.
    """
    output_dir = output_dir or os.path.join(OUTPUT_DIR, 'packages', 'narrative')
    os.makedirs(output_dir, exist_ok=True)

    total_paid = summary_stats.get('total_paid_analyzed', 0)
    total_providers = summary_stats.get('total_providers', 0)
    total_findings = summary_stats.get('total_findings', 0)
    estimated_recoverable = summary_stats.get('estimated_recoverable', 0)
    high_risk = summary_stats.get('high_risk_providers', 0)

    narrative = f"""# Medicaid Fraud, Waste & Abuse Analysis — Summary Narrative

## Overview

This analysis examined {format_dollars(total_paid)} in Medicaid provider payments \
spanning January 2018 through December 2024. The dataset covered {total_providers:,} \
providers billing across thousands of procedure codes.

## What We Found

The analytics pipeline identified {total_findings:,} potential findings across \
multiple detection methods, including statistical outlier detection, temporal pattern \
analysis, peer comparison, network analysis, and domain-specific rules.

The estimated recoverable amount is {format_dollars(estimated_recoverable)}. \
Of the {total_providers:,} providers analyzed, {high_risk:,} were classified as \
high-risk based on composite scoring across all detection methods.

## Highest Priority Providers

"""

    for i, f in enumerate(top_findings[:5], 1):
        npi = f.get('npi', f.get('flagged_providers', ['Unknown'])[0])
        impact = f.get('total_impact', 0)
        evidence = f.get('evidence', 'Multiple detection methods flagged this provider.')
        narrative += f"""### {i}. Provider {npi}

Estimated impact: {format_dollars(impact)}

{evidence}

"""

    narrative += """## What Happens Next

These findings require human review by trained investigators. The priority queue \
ranks providers by estimated financial impact and confidence level. Providers \
matched against the OIG exclusion list should be prioritized for immediate review.

---

*This narrative was generated by the Medicaid FWA Analytics Pipeline to provide \
a non-technical summary of analytical results.*
"""

    path = os.path.join(output_dir, 'narrative_summary.md')
    with open(path, 'w') as f:
        f.write(narrative)

    logger.info(f'Generated narrative summary: {path}')
    return path


def generate_provider_narrative(provider_data):
    """Generate a plain-language summary for a single provider.

    Args:
        provider_data: dict from research/sandbox.run_provider_deep_dive.

    Returns:
        string with the narrative text.
    """
    npi = provider_data.get('npi', 'Unknown')
    summary = provider_data.get('summary', {})
    total_paid = summary.get('total_paid', 0)
    total_claims = summary.get('total_claims', 0)
    num_months = summary.get('num_months', 0)
    top_codes = provider_data.get('top_codes', [])

    lines = [
        f'Provider {npi} billed {format_dollars(total_paid)} across '
        f'{total_claims:,} claims over {num_months} months.',
    ]

    if top_codes:
        top = top_codes[0]
        lines.append(
            f'Their most billed procedure code was {top["code"]}, '
            f'accounting for {format_dollars(top["paid"])} ({top["claims"]:,} claims).'
        )

    return ' '.join(lines)
